---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: backenddeployment
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  selector: 
    matchLabels:
      app: backendapp
  template: 
    metadata:
      name: backendapppod
      labels:
        app: backendapp
    spec:
      containers:
        name: backendcont
        image: zaidp/backendimage
        ports:
        - port: 80
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backendsvc
spec:
  type: LoadBalancer
  selector:
    app: backendapp
  ports:
  - port: 80
    targetPort: 8080
...
