---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: backenddeployment
spec:
 replicas: 1
 selector:
   matchLabels:
     app: backendapp
 template:
  metadata:
   name: backendapp
   labels:
     app: backendapp
  spec:
    containers:
    - name: contactbackendcontainer
      image: zaidp//backendimage
      ports:
      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
 name: backendsvc
spec:
  type: LoadBalancer
  selector:
   app: backendapp
  ports:
   - port: 80
     targetPort: 8080
...
